name: Build and Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - run: uv python install
      - run: uv build
      - run: uv publish
